version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - database_vol:/data/db

  backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - internal_job_portal_vol:/app
      - internal_job_portal_upload:/app/upload
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

volumes:
  database_vol:
  internal_job_portal_vol:
  internal_job_portal_upload: