export const YearData = [
   { value: 1900 },
   { value: 1901 },
   { value: 1902 },
   { value: 1903 },
   { value: 1904 },
   { value: 1905 },
   { value: 1906 },
   { value: 1907 },
   { value: 1908 },
   { value: 1909 },
   { value: 2000 },
   { value: 2001 },
   { value: 2002 },
   { value: 2003 },
   { value: 2004 },
   { value: 2005 },
   { value: 2006 },
];

export const MonthData = [
   { value: 'January' },
   { value: 'February' },
   { value: 'March' },
   { value: 'April' },
   { value: 'May' },
   { value: 'June' },
   { value: 'July' },
   { value: 'August' },
   { value: 'September' },
   { value: 'October' },
   { value: 'November' },
   { value: 'December' },
];

export const DateData = [
   { value: 1 },
   { value: 2 },
   { value: 3 },
   { value: 4 },
   { value: 5 },
   { value: 6 },
   { value: 7 },
   { value: 8 },
   { value: 9 },
   { value: 10 },
   { value: 11 },
   { value: 12 },
   { value: 13 },
   { value: 14 },
   { value: 15 },
   { value: 16 },
   { value: 17 },
   { value: 18 },
   { value: 19 },
   { value: 20 },
   { value: 21 },
   { value: 22 },
   { value: 23 },
   { value: 24 },
   { value: 25 },
   { value: 26 },
   { value: 27 },
   { value: 28 },
   { value: 29 },
   { value: 30 },
   { value: 31 },
];

export const Career = [
   { value: 'New Grand' },
   { value: 'No Experience' },
   { value: 'Student' },
   { value: 'Experienced' },
   { value: 'Executive' },
];

export const Experience = [
   { value: 'Less then 1 year' },
   { value: '1 year' },
   { value: '2 year' },
   { value: '3 year' },
   { value: '4 year' },
   { value: '5 year' },
   { value: '6 year' },
   { value: '7 year' },
   { value: '8 year' },
   { value: '9 year' },
   { value: '10+' },
];
